[[redirects]]
  from = "https://batuhanurush.com/*"
  to = "https://kant.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://philipkant.com/*"
  to = "https://kant.dev/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://phillipkant.com/*"
  to = "https://kant.dev/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://batuhanurush.de/*"
  to = "https://kant.dev/:splat"
  status = 301
  force = true